env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 13
  sourceType: module
  project:
    - "tsconfig.json"
plugins:
  - "@typescript-eslint"
  - "simple-import-sort"
rules:
  indent:
    - off
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - never
  require-await: off
  no-unused-vars: off
  "simple-import-sort/imports": "error"
  "simple-import-sort/exports": "error"
  "@typescript-eslint/no-unused-vars": error
  "@typescript-eslint/prefer-optional-chain": error
  "@typescript-eslint/array-type": error
  "@typescript-eslint/no-explicit-any": error
  "@typescript-eslint/no-redundant-type-constituents": error
  "@typescript-eslint/no-throw-literal": error
  "@typescript-eslint/prefer-as-const": error
  "@typescript-eslint/require-await": error
  "@typescript-eslint/switch-exhaustiveness-check": warn
  "@typescript-eslint/consistent-type-definitions":
    - error
    - interface
